# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Frankenzyme
tagline:          'Surface Screen Results'
description:      ''
url:              http://frankenzyme.com
baseurl:          /

author:
  name:           'T. Andrew Binkowski'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
